# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia
os:
  - linux
julia:
  - 1.3
  - 1.5
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  include:
    - stage: "test"
      julia: 1.5
      os: linux
      script:
        - julia --project=. -e 'using Pkg;
                                Pkg.develop(PackageSpec(path=pwd()));
                                Pkg.instantiate()'
        - julia --project=. --color=yes --check-bounds=yes test/GridapTests/runtests.jl
      after_success: skip
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip


